In [1]:
!pip install hvplot

In [2]:
import numpy as np
import pandas as pd
import time

import sklearn.metrics as metrics
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.utils import to_categorical
from keras import models
from keras import layers

In [3]:

import holoviews as hv
import panel as pn
import hvplot
import hvplot.pandas
hv.extension('bokeh')

In [4]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=UserWarning)

In [5]:
X = np.arange(10).reshape(-1, 1)
y = np.array([0., 0., 1., 0., 0., 1., 1., 1., 1., 1.])
y = to_categorical(y)

In [6]:
print(X)
print(y)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]


In [7]:
model = models.Sequential()
model.add(layers.Dense(3,kernel_initializer='RandomNormal', activation='sigmoid'))
model.add(layers.Dense(2,activation='softmax'))
model.compile(loss='binary_crossentropy', optimizer=keras.optimizers.Nadam(learning_rate=0.4), metrics=['accuracy'])

In [8]:
history = model.fit(X, y, epochs=300)

Epoch 1/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step - accuracy: 0.4000 - loss: 0.7543
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 225ms/step - accuracy: 0.6000 - loss: 0.6939
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 0.6000 - loss: 0.6669
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 0.6000 - loss: 0.6479
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - accuracy: 0.6000 - loss: 0.6257
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - accuracy: 0.8000 - loss: 0.5980
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - accuracy: 0.8000 - loss: 0.5654
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.7000 - loss: 0.5313
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.7000 - loss: 0.4995
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.8000 - loss: 0.4721
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.8000 - loss: 0.4497
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.8000 

In [9]:
pd.DataFrame(history.history).hvplot.line( x='index',
                  line_width=3,
                  legend='top',   widget_location='left',
                  grid = True, xlabel='Эпоха обучения', ylabel='Значение',
                  height=400, width=700)

HoloViews(NdOverlay, height=400, sizing_mode='fixed', widget_location='left', width=700)

In [10]:
z = model.predict(X)
z

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step


array([[9.9999923e-01, 6.8157931e-07],
       [9.9999815e-01, 1.8171023e-06],
       [3.5542045e-05, 9.9996442e-01],
       [9.9998790e-01, 1.2010884e-05],
       [9.9997431e-01, 2.5632280e-05],
       [2.0514242e-05, 9.9997944e-01],
       [8.0067377e-07, 9.9999911e-01],
       [7.4617918e-07, 9.9999923e-01],
       [7.4516879e-07, 9.9999928e-01],
       [7.4514958e-07, 9.9999928e-01]], dtype=float32)

In [11]:
res_df=pd.DataFrame({'X': X[:,0], 'Y_train':y[:,1], 'Y_pred': z[:,1]})
p1=res_df.hvplot.scatter( x='X',  marker='circle', size=150, alpha=0.75, legend='top' )
p2=res_df.hvplot.line( x='X',  y=['Y_pred'],  line_width=3, line_dash='dashed', legend='top')
p2.opts(title='Обучение NN2: Класс 1', show_grid = True, xlabel='X', ylabel='Y', height=400, width=700)
(p2 * p1).opts(title='Обучение NN2: Класс 1', show_grid = True, xlabel='X', ylabel='Y', height=400, width=700)

:Overlay
   .Curve.I     :Curve   [X]   (Y_pred)
   .NdOverlay.I :NdOverlay   [Variable]
      :Scatter   [X]   (value)

In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 3)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 2)                   │               8 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 45 (184.00 B)

 Trainable params: 14 (56.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 31 (128.00 B)